# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_remove_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='edited_image',
            field=models.ImageField(blank=True, upload_to='edited'),
        ),
    ]
